### ISSUE TITLE
build-plugin-component会有计划支持vite吗？

### ISSUE THREAD

**Issue by xmsz** [ice-lab/pkg-cli#289]
背景
- 想用vite加快构建速度
- 想使用vite的一些插件

**Comment by maoxiaoke** [comment]
@xmsz  没有计划

**Comment by xmsz** [comment]
> @xmsz 没有计划

ok

**Comment by maoxiaoke** [comment]
@xmsz 组件开发正出于 beta 中，https://github.com/ice-lab/pkg-cli/tree/feat/move-component-next-2。预览层面使用 https://docusaurus.io/，提供更快，更好的预览能力。可以尝试一下
